apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1m
  chart:
    spec:
      chart: vault
      version: '0.25.0'
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      dev:
        enabled: true
    ui:
      enabled: true
